#!/bin/sh

power=$(upower -i $(upower -e | grep BAT0) | grep -E "state" | cut -d ':' -f 2 | sed 's/ //g')

if [ "discharging" = "$power" ]; then
	logger "LID closed while discharging, suspending"
	zzz
else
	logger "LID closed while on power, locking screen"
	slock
fi


#new
if [ -f /tmp/caffeinated ]; then
	logger "LID closed while caffeinated, locking screen"
	slock
	return;
fi
logger "LID closed, suspending..."
zzz
