# Config definitions.

xresources:
  path: "~/.config/xrdb/Xresources.xdefaults"
  regex: '#include ".*\.xdefaults"'
  pre: '#include "./'
  post: '.xdefaults"'
  cmd: "reload_xrdb"

vim:
  path: "~/.config/nvim/lua/visual.lua"
  regex: 'cmd "colorscheme .*"'
  pre: 'cmd "colorscheme '
  post: '"'
  cmd: "all_nvim 'colorscheme %'"

lualine:
  path: "~/.config/nvim/lua/statusline.lua"
  regex: '.*options = { theme = ".*" }'
  pre: '        options = { theme = "'
  post: '" }'
  cmd: "all_nvim 'lua Reload_statusline(\"%\")'"

# lightline:
#   path: "~/.config/nvim/init.vim"
#   regex: '    \\   "colorscheme" : .*'
#   pre: '    \   "colorscheme" : "'
#   post: '",'
#   cmd: "all_nvim 'source $MYVIMRC'"

