# Config definitions.

xresources:
  type: colorscheme
  path: "~/.config/xrdb/selected_theme.xdefaults"
  regex: '#include ".*\.xdefaults"'
  pre: '#include "./'
  post: '.xdefaults"'
  cmd: "reload_xrdb"

nvim:
  type: colorscheme
  path: "~/.config/nvim/lua/user/visual.lua"
  regex: 'cmd "colorscheme .*"'
  pre: 'cmd "colorscheme '
  post: '"'
  cmd: "all_nvim 'colorscheme %'"

lualine:
  type: colorscheme
  path: "~/.config/nvim/lua/user/statusline.lua"
  regex: '.*local theme = ".*"'
  pre: 'local theme = "'
  post: '"'
  cmd: "all_nvim 'lua ReloadStatusline(\"%\")'"

polybar:
  path: "~/.config/polybar/config.ini"
  regex: '^include-file = .*\.ini'
  pre: 'include-file = ./'
  post: '.ini'

# lightline:
#   path: "~/.config/nvim/init.vim"
#   regex: '    \\   "colorscheme" : .*'
#   pre: '    \   "colorscheme" : "'
#   post: '",'
#   cmd: "all_nvim 'source $MYVIMRC'"

