# Config definitions.

xresources:
  type: colorscheme
  path: "~/.config/xrdb/selected_theme.xdefaults"
  regex: '#include ".*\.xdefaults"'
  replace: '#include "./{}.xdefaults"'
  # pre: '#include "./'
  # post: '.xdefaults"'
  cmd: "reload_xrdb"

nvim:
  type: colorscheme
  path: "~/.config/nvim/lua/user/visual.lua"
  regex: 'cmd "colorscheme .*"'
  replace: 'cmd "colorscheme {}"'
  cmd: "all_nvim 'colorscheme {}'"

lualine:
  type: colorscheme
  path: "~/.config/nvim/lua/user/statusline.lua"
  regex: '.*local theme = ".*"'
  replace: 'local theme = "{}"'
  cmd: "all_nvim 'lua ReloadStatusline(\"{}\")'"

polybar:
  type: polybar
  path: "~/.config/polybar/config.ini"
  regex: 'include-file = .*\.ini'
  replace: 'include-file = ./{}.ini'
  cmd: "bspc config top_padding 0"

    # color_scheme = "TokyoNight (Gogh)",
wezterm:
  type: colorscheme
  path: "~/.config/wezterm/wezterm.lua"
  regex: '    color_scheme = ".*",'
  replace: '    color_scheme = "{}",'

sxhkd:
  type: terminal
  path: "~/.config/sxhkd/sxhkdrc"
  regex: '.*!!!themr marker:terminal'
  replace: '  {} # !!!themr marker:terminal'
  cmd: pkill --signal USR1 sxhkd

picom:
  type: picom
  path: "~/.config/picom.conf"
  regex: ".*corner-radius = .*# themr #"
  replace: "corner-radius = {} # themr #"

bspwm-single_monocle:
  type: bspwm-single_monocle
  path: "~/.config/bspwm/bspwmrc"
  regex: ".* single_monocle .* # themr:bspwm-single_monocle #"
  replace: "bspc config single_monocle {} # themr:bspwm-single_monocle #"
  cmd: "bspc config single_monocle {}"

bspwm-window_gap:
  type: bspwm-window_gap
  path: "~/.config/bspwm/bspwmrc"
  regex: ".* window_gap .* # themr:bspwm-window_gap #"
  replace: "bspc config window_gap {} # themr:bspwm-window_gap #"
  cmd: "bspc config window_gap {}"

term_env_var:
  type: terminal
  path: "~/bin/exports"
  regex: 'export TERMINAL=.*'
  replace: 'export TERMINAL="{}"'


# lightline:
#   path: "~/.config/nvim/init.vim"
#   regex: '    \\   "colorscheme" : .*'
#   pre: '    \   "colorscheme" : "'
#   post: '",'
#   cmd: "all_nvim 'source $MYVIMRC'"

