# Config definitions.

xresources:
  type: colorscheme
  path: "~/.config/xrdb/selected_theme.xdefaults"
  regex: '#include ".*\.xdefaults"'
  replace: '#include "./{}.xdefaults"'
  # pre: '#include "./'
  # post: '.xdefaults"'
  cmd: "reload_xrdb"

nvim:
  type: colorscheme
  path: "~/.config/nvim/lua/user/visual.lua"
  regex: 'cmd "colorscheme .*"'
  replace: 'cmd "colorscheme {}"'
  cmd: "all_nvim 'colorscheme {}'"

lualine:
  type: colorscheme
  path: "~/.config/nvim/lua/user/statusline.lua"
  regex: '.*local theme = ".*"'
  replace: 'local theme = "{}"'
  cmd: "all_nvim 'lua ReloadStatusline(\"{}\")'"

polybar:
  type: polybar
  path: "~/.config/polybar/config.ini"
  regex: 'include-file = .*\.ini'
  replace: 'include-file = ./{}.ini'
  cmd: "bspc config top_padding 0"

    # color_scheme = "TokyoNight (Gogh)",
wezterm:
  type: colorscheme
  path: "~/.config/wezterm/wezterm.lua"
  regex: '    color_scheme = ".*",'
  replace: '    color_scheme = "{}",'

sxhkd:
  type: terminal
  path: "~/.config/sxhkd/sxhkdrc"
  regex: '.*!!!themr marker:terminal'
  replace: '  {} # !!!themr marker:terminal'
  cmd: pkill --signal USR1 sxhkd

term_env_var:
  type: terminal
  path: "~/bin/exports"
  regex: 'export TERMINAL=.*'
  replace: 'export TERMINAL="{}"'


# lightline:
#   path: "~/.config/nvim/init.vim"
#   regex: '    \\   "colorscheme" : .*'
#   pre: '    \   "colorscheme" : "'
#   post: '",'
#   cmd: "all_nvim 'source $MYVIMRC'"

