local lsp_icons = {
	cozette = {
		Text = '󰉿', --   󰉿
		Method = '∈', -- ?
		Function = '',
		Constructor = '',
		Field = '',
		Variable = '⍺',
		Class = '', -- 
		Interface = '⌘', -- 
		Module = '',
		Property = '∷', -- ?
		Unit = '€', --  ruler?
		Value = '',
		Enum = '',
		Keyword = '',
		Snippet = '謹',
		Color = '',
		File = '',
		Reference = '⇒', -- ?
		Folder = '',
		EnumMember = '',
		Constant = '',
		Struct = '󰙅',
		Event = '',
		Operator = '±',
		TypeParameter = '∀',
	},
	nerd = {
		Text = '󰉿',
		Method = '∈',
		Function = '󰊕',
		Constructor = '',
		Field = '',
		Variable = '⍺',
		Class = '󰅩',
		Interface = '⌘',
		Module = '󰆧',
		Property = '∷',
		Unit = '€',
		Value = '󰎠',
		Enum = '',
		Keyword = '󰌋',
		Snippet = '󰗀',
		Color = '󰏘',
		File = '󰈙',
		Reference = '⇒',
		Folder = '󰉋',
		EnumMember = '',
		Constant = '󰏿',
		Struct = '󰙅',
		Event = '',
		Operator = '±',
		TypeParameter = '∀',
	},
	vscode = {
		Text = '  ',
		Method = '  ',
		Function = '  ',
		Constructor = '  ',
		Field = '  ',
		Variable = '  ',
		Class = '  ',
		Interface = '  ',
		Module = '  ',
		Property = '  ',
		Unit = '  ',
		Value = '  ',
		Enum = '  ',
		Keyword = '  ',
		Snippet = '  ',
		Color = '  ',
		File = '  ',
		Reference = '  ',
		Folder = '  ',
		EnumMember = '  ',
		Constant = '  ',
		Struct = '  ',
		Event = '  ',
		Operator = '  ',
		TypeParameter = '  ',
	},
}
local icons = {
	diagnostic = {
		error = ' ',
		warn = ' ',
		info = ' ',
		hint = '󰌵 ',
	},
	fold = { -- WARN: single char wide
		close = '›',
		open = '⌵',
		sep = ' ',
		-- close = "",
		-- open = "",
	},
	line = {
		short = '⏽',
		center_dotted = '┊',
		center_line = '│',
		left_thin = '▏',
		left_medium = '▎',
		left_thick = '▊',
		right_thin = '▕',
	},
	misc = {
		neovim = ' ',
		vim = ' ',
		check = ' ',
		close = ' ',
		grep = ' ',
		right_arrow = '➜',
		search = '⌕ ', -- 󰃬
		settings = ' ',
		settings2 = ' ',
		term = ' ',
		x = '✗',
		circle_dot = ' ',
		circle_check = '󰄳 ',
		dead = '󰚌 ',
	},
	listchars = {
		nbsp = '␣',
		trail = '·',
		-- tab = '   ',
		tab = '▏  ',
		eol = '↲ ',
	},
	file = {
		normal = ' ',
		modilied = '●',
		pinned = '󰐃 ',
	},
	git = {
		branch = ' ',
	},
	diff = {
		outline = {
			added = ' ',
			modified = ' ',
			removed = ' ',
		},
		bold = {
			added = ' ',
			modified = '  ',
			removed = ' ',
		},
		cozette = {
			added = ' ',
			removed = ' ',
			modilied = ' ',
		},
	},
	progress = { '██', '▇▇', '▆▆', '▅▅', '▄▄', '▃▃', '▂▂', '▁▁', '  ' },
	border = {
		square = {
			top_left = '┌',
			top_right = '┐',
			bottom_left = '└',
			bottom_right = '┘',
			horizontal = '─',
			vertical = '│',
		},
		round = {
			top_left = '╭',
			top_right = '╮',
			bottom_left = '╰',
			bottom_right = '╯',
			horizontal = '─',
			vertical = '│',
		},
	},
	lazy = {
		cmd = ' ',
		config = '',
		event = '',
		ft = ' ',
		init = ' ',
		import = ' ',
		keys = ' ',
		lazy = '󰒲 ',
		loaded = '●',
		not_loaded = '○',
		plugin = ' ',
		runtime = ' ',
		require = '󰢱 ',
		source = ' ',
		start = '⏵',
		task = '✔ ',
		list = { '●', '➜', '✭', '‒' },
	},
}

icons.lsp = lsp_icons.nerd

return icons
