# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '$all$fill$cmd_duration$line_break$character'

[username]
show_always = false

[hostname]
ssh_only = true
ssh_symbol = ""

[character]
#symbol cache :) = "❯ "
success_symbol = "[ε](bold green)"
error_symbol = "[α](bold red)"
vicmd_symbol = "[v](bold blue)"
# use_symbol_for_status = true

[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "

[fill]
symbol = " "

[cmd_duration]
show_milliseconds = true

[aws]
disabled = true

# [conda]
# symbol = "  "

[cmake]
disabled = true

[crystal]
disabled = true

[c]
symbol = " "
disabled = false

[cpp]
symbol = " "
disabled = false

[dart]
disabled = true

[directory]
# read_only = " "

[docker_context]
disabled = true
symbol = "  "

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[golang]
symbol = " "

[gcloud]
disabled = true

[git_branch]
# symbol = "󰘬 "

[git_metrics]
disabled = false

[git_status]
# conflicted = '='
# ahead = ''
# behind = ''
# diverged = ' '
# up_to_date = ''
untracked = '?'
stashed = '\$'
modified = '!'
# staged = ' '
# renamed = '»' 
# deleted = ' '
# typechanged = ''
# windows_starship = '/mnt/c/something'

[helm]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
symbol = " "

[memory_usage]
# symbol = " "
disabled = false

[nix_shell]
symbol = "  "

# [nodejs]
# symbol = "  "

[ocaml]
disabled = true

[openstack]
disabled = true

# [package]
# symbol = " "

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[python]
symbol = " "

[ruby]
disabled = true

[rust]
symbol = ""
disabled = false

[singularity]
disabled = true

[scala]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[vagrant]
disabled = true

[zig]
disabled = false
