# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[username]
show_always = false

[hostname]
ssh_only = true
ssh_symbol = ""

[character]
#symbol cache :) = "❯ "
success_symbol = "[ε](bold green)"
error_symbol = "[α](bold red)"
vicmd_symbol = "[v](bold blue)"
# use_symbol_for_status = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[aws]
disabled = true

[conda]
symbol = " "

[cmake]
disabled = true

[crystal]
disabled = true

[c]
disabled = true

[dart]
disabled = true

[directory]
read_only = " "

[docker_context]
disabled = true
symbol = " "

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[helm]
disabled = true

[hg_branch]
symbol = " "
disabled = true

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
disabled = true

[kubernetes]
disabled = true

[memory_usage]
symbol = " "
disabled = false

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
symbol = " "

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[python]
symbol = " "

[rlang]
symbol = "Rﱨ "

[ruby]
disabled = true

[rust]
symbol = " "
disabled = false

[singularity]
disabled = true

[scala]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[vagrant]
disabled = true

[zig]
disabled = false

