#!/bin/sh

xrandr --output HDMI1 --mode 1920x1080 --right-of LVDS1
xrandr --output LVDS1 --mode 1600x900 
~/.fehbg &

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar_start &

# HACK: use first result as default monitor
MONITOR=$(xrandr | grep ' connected' | head -1 | cut -d ' ' -f1)

bspc monitor "$MONITOR" --reset-desktops I II III IV V VI
# bspc wm --reorder-monitors HDMI1 LVDS1
# bspc monitor HDMI1 --reset-desktops I II III IV V VI
# bspc monitor LVDS1 --reset-desktops I II III IV V VI


DB=$(xrdb -query)
active=$(echo "$DB" | grep 'polybar.active' | cut -f 2 -d ':' | sed 's/\t//')
bspc config focused_border_color "$active"

bspc config border_width 4
bspc config window_gap   4
bspc config split_ratio          0.50

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled
bspc rule -a Vivaldi-stable desktop='^1'
bspc rule -a Screenkey manage=off
bspc rule -a MEGAsync state=floating
bspc rule -a discord desktop='^5'
bspc rule -a Barrier state=floating #desktop='^6' 
bspc rule -a kdeconnect.app desktop='^6' state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Blueman-manager state=floating

# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
