#!/bin/sh

xrandr --output VGA1 --mode 1920x1080 --right-of LVDS1
# xrandr --output LVDS1 --mode 1600x900 
~/.fehbg &

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar_start &

bspc wm --reorder-monitors VGA1 LVDS1 
bspc monitor VGA1 --reset-desktops I II III
bspc monitor LVDS1 --reset-desktops IV V VI 

bspc config border_width         4
bspc config window_gap          4

DB=$(xrdb -query)
active=$(echo "$DB" | grep 'polybar.active' | cut -f 2 -d ':' | sed 's/\t//')
bspc config focused_border_color "$active"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a MEGAsync state=floating
bspc rule -a discord desktop='^5'
bspc rule -a kdeconnect.app desktop='^6' state=floating
bspc rule -a barrier desktop='^6' state=floating
bspc rule -a Pavucontrol desktop='^6' state=floating
bspc rule -a Blueman-manager desktop='^6' state=floating
