[colors]
ansi = [
    '#222222',
    '#ff869a',
    '#c3e88d',
    '#ffcb6b',
    '#82b1ff',
    '#c792ea',
    '#89ddff',
    '#bfc7d5',
]
background = '#292D3E'
brights = [
    '#181a1f',
    '#ff5370',
    '#c3f05d',
    '#efef22',
    '#72a1ff',
    '#c772ea',
    '#79ddff',
    '#f8f8f8',
]
# cursor_bg = '#202746'
# cursor_border = '#979db4'
cursor_fg = '#2C323C'
foreground = '#bfc7d5'
# selection_bg = '#5e6687'
# selection_fg = '#979db4'

[colors.indexed]

[metadata]
name = 'palenight'
