[colors]
ansi = [
    '#eee8d5',
    '#dc322f',
    '#859900',
    '#b58900',
    '#268bd2',
    '#d33682',
    '#2aa198',
    '#002b36',
]
background = '#eee8d5'
brights = [
    '#fdf6e3',
    '#cb4b16',
    '#93a1a1',
    '#839496',
    '#657b83',
    '#6c71c4',
    '#586e75',
    '#073642',
]
# cursor_bg = '#202746'
# cursor_border = '#979db4'
cursor_fg = '#002b36'
foreground = '#002b36'
# selection_bg = '#5e6687'
# selection_fg = '#979db4'

[colors.indexed]

[metadata]
name = 'solarized_light'
