[colors]
ansi = [
    '#1d202f',
    '#f7768e',
    '#9ece6a',
    '#e0af68',
    '#7aa2f7',
    '#bb9af7',
    '#7dcfff',
    '#a9b1d6',
]
background = '#24283b'
brights = [
    '#414868',
    '#f7768e',
    '#9ece6a',
    '#e0af68',
    '#7aa2f7',
    '#bb9af7',
    '#7dcfff',
    '#c0caf5',
]
# cursor_bg = '#202746'
# cursor_border = '#979db4'
cursor_fg = '#c0caf5'
foreground = '#c0caf5'
# selection_bg = '#5e6687'
# selection_fg = '#979db4'

[colors.indexed]

[metadata]
name = 'tokyonight_storm'
