[colors]
ansi = [
    '#e9e9ed',
    '#f52a65',
    '#587539',
    '#8c6c3e',
    '#2e7de9',
    '#9854f1',
    '#007197',
    '#6172b0',
]
background = '#e1e2e7'
brights = [
    '#a1a6c5',
    '#f52a65',
    '#587539',
    '#8c6c3e',
    '#2e7de9',
    '#9854f1',
    '#007197',
    '#3760bf',
]
# cursor_bg = '#202746'
# cursor_border = '#979db4'
cursor_fg = '#3760bf'
foreground = '#3760bf'
# selection_bg = '#5e6687'
# selection_fg = '#979db4'

[colors.indexed]

[metadata]
name = 'tokyonight_day'
