[colors]
foreground    = "#BED6FA"
background    = "#04080E"
cursor_fg     = "#04080E"
cursor_bg     = "#BED6FA"
cursor_border = "#7B541A"
selection_fg  = "#04080E"
selection_bg  = "#29415F"
ansi = ["#020408", "#F68895", "#83B83B", "#E1CA46", "#68ADF4", "#D58DEC", "#40BAB4", "#B3CBED"]
brights = ["#1C242F", "#EA2641", "#4DB554", "#E19A3C", "#215E99", "#D58DEC", "#79B3AF", "#9C9C88"]
