[username]
show_always = false

[hostname]
ssh_only = true

[character]
#symbol cache :) = "❯ "
success_symbol = "[ε](bold green)"
error_symbol = "[x](bold red)"
# use_symbol_for_status = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[aws]
symbol = " "
style = "yellow"
disabled = true

[conda]
symbol = " "

[cmake]
disabled = true

[crystal]
disabled = true

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
disabled = true
symbol = " "

[dotnet]
disabled = true

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

# [haskell]
# symbol = " "

[helm]
disabled = true

[hg_branch]
symbol = " "
disabled = true

[java]
symbol = " "

[julia]
symbol = " "
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[memory_usage]
symbol = " "
disabled = false

[nim]
symbol = " "
disabled = true

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
symbol = " "

[perl]
symbol = " "
disabled = true

[php]
symbol = " "

[purescript]
disabled = true

[python]
symbol = " "

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
disabled = true

[singularity]
disabled = true

[scala]
symbol = " "
disabled = true

[swift]
symbol = "ﯣ "
disabled = true

[terraform]
disabled = true

[vagrant]
disabled = true

[zig]
disabled = true

