[username]
show_always = false

[hostname]
ssh_only = true

[character]
symbol = "❯ "
error_symbol = " "
use_symbol_for_status = true
style_success = "green"
style_failure = "red"

[aws]
symbol = " "
style = "yellow"

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[git_branch]
style = "purple"
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
