source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "lePerdu/kakboard" %{
        hook global WinCreate .* %{ kakboard-enable }
}
plug "alexherbo2/auto-pairs.kak"
plug "ul/kak-lsp" do %{
    cargo install --locked --force --path .
} config %{

    # uncomment to enable debugging
    # eval %sh{echo ${kak_opt_lsp_cmd} >> /tmp/kak-lsp.log}
    # set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"

    # this is not necessary; the `lsp-enable-window` will take care of it
    # eval %sh{${kak_opt_lsp_cmd} --kakoune -s $kak_session}

    set global lsp_diagnostic_line_error_sign '║'
    set global lsp_diagnostic_line_warning_sign '┊'

    define-command ne -docstring 'go to next error/warning from lsp' %{ lsp-find-error --include-warnings }
    define-command pe -docstring 'go to previous error/warning from lsp' %{ lsp-find-error --previous --include-warnings }
    define-command ee -docstring 'go to current error/warning from lsp' %{ lsp-find-error --include-warnings; lsp-find-error --previous --include-warnings }

    define-command lsp-restart -docstring 'restart lsp server' %{ lsp-stop; lsp-start }
    hook global WinSetOption filetype=(c|cpp|cc|rust|javascript|typescript) %{
        set-option window lsp_auto_highlight_references true
        set-option window lsp_hover_anchor false
        lsp-auto-hover-enable
        echo -debug "Enabling LSP for filtetype %opt{filetype}"
        lsp-enable-window
    }

    hook global WinSetOption filetype=(rust) %{
        set window lsp_server_configuration rust.clippy_preference="on"
    }

    hook global WinSetOption filetype=rust %{
        hook window BufWritePre .* %{
            evaluate-commands %sh{
                test -f rustfmt.toml && printf lsp-formatting-sync
            }
        }
    }

    hook global KakEnd .* lsp-exit
}

set-option global tabstop 4
set-option global indentwidth 4
set-option global scrolloff 6,6
set-option global tabstop 4



add-highlighter global/ number-lines
colorscheme palenight


hook global InsertCompletionShow .* %{
    map window insert <tab> '<c-n>'
    map window insert <s-tab> '<c-p>'
    map window insert <ret> '<c-y>'
    map window insert <s-ret> '<ret>'
    }


hook global InsertCompletionHide .* %{
    unmap window insert <tab> '<c-n>'
    unmap window insert <s-tab> '<c-p>'
    unmap window insert <ret> '<c-y>'
    unmap window insert <s-ret> '<ret>'
    }

















