#!/bin/sh

DB=$(xrdb -query)

red=$(echo "$DB" | grep 'color1:' | cut -f 2 -d ':' | sed 's/\t//')
green=$(echo "$DB" | grep 'color2:' | cut -f 2 -d ':' | sed 's/\t//')
blue=$(echo "$DB" | grep 'color4:' | cut -f 2 -d ':' | sed 's/\t//')
background=$(echo "$DB" | grep '\*background:' | cut -f 2 -d ':' | sed 's/\t//')

theme="
[urgency_low]
frame_color = \"$blue\"
foreground = \"$blue\"
background = \"$background\"
timeout = 4

[urgency_normal]
frame_color = \"$green\"
foreground = \"$green\"
background = \"$background\"
timeout = 6

[urgency_critical]
frame_color = \"$red\"
foreground = \"$red\"
background = \"$background\"
timeout = 8
"

# cp dunstrc $(date "+%Y-%m-%d-%H-%M-%S").dunstrc
cp ./no_theme.dunstrc dunstrc
echo "$theme" >> dunstrc

# pkill dunst
notify-send -u low 'Reloaded dunstrc!'
