#!/bin/bash

DB=$(xrdb -query)

red=$(echo "$DB" | grep 'color1:' | cut -f 2 -d ':' | sed 's/\t//')
green=$(echo "$DB" | grep 'color2:' | cut -f 2 -d ':' | sed 's/\t//')
# blue=$(echo "$DB" | grep 'color4:' | cut -f 2 -d ':' | sed 's/\t//')
blue=$(echo "$DB" | grep 'dwm.selbordercolor:' | cut -f 2 -d ':' | sed 's/\t//')
background=$(echo "$DB" | grep '\*background:' | cut -f 2 -d ':' | sed 's/\t//')
# TODO:
# font=$(echo "$DB" | grep '^\*font:' | cut -f 2 -d ':' | sed 's/\t//')
# font_size=$(echo "$DB" | grep '^\*font:' | cut -f 3 -d ':' | sed 's/\t//')

theme="
[urgency_low]
frame_color = \"$blue\"
foreground = \"$blue\"
background = \"$background\"
timeout = 4

[urgency_normal]
frame_color = \"$green\"
foreground = \"$green\"
background = \"$background\"
timeout = 6

[urgency_critical]
frame_color = \"$red\"
foreground = \"$red\"
background = \"$background\"
timeout = 8

# vim: ft=cfg
"

CONF_PATH="$HOME/.config/dunst"

# cp dunstrc $(date "+%Y-%m-%d-%H-%M-%S").dunstrc
# cp $CONF_PATH/no_theme.dunstrc $CONF_PATH/dunstrc
head -n -1 "$CONF_PATH/no_theme.dunstrc" > $CONF_PATH/dunstrc
echo "$theme" >> "$CONF_PATH"/dunstrc

pkill ^dunst # --echo 
notify-send -u low 'Changed theme!'
